raw_dir: "data/raw"
geospatial_dir: "data/raw/geospatial"
gbfif_dir: "data/raw/gbif"

interim_dir : "data/interim"
processed_dir: "data/processed"
db_dir: "data/db"

geospatial_files:
  - grid.shp
  - parks.shp
  - quartiers.shp
  
limit: 1000