data_dir: "data"
raw_dir: "data/raw"
interim_dir : "data/interim"
processed_dir: "data/processed"
db_dir: "data/db"

limit: None
target_crs: 4326

duckdb_file: "data/db/mtlBio.duckdb"

grid_size: 250

wkt_filters: ["filters/filter1.wkt"]

gbif_columns: "gbifID,
                occurrenceID,
                kingdom,
                phylum,
                class,
                order,
                family,
                genus,
                species,
                taxonRank,
                scientificName,
                eventDate,
                day,
                month,
                year,
                taxonKey,
                basisOfRecord,
                license,
                recordedBy,
                issue,
                publishingOrgKey,
                coordinateUncertaintyInMeters,
                geom
                "
               
