data_dir: "data"
raw_dir: "data/raw"
interim_dir : "data/interim"
processed_dir: "data/processed"
db_dir: "data/db"

limit: 1000
target_crs: 4326



shapefiles:
  - name: "grid"
  - name: "grid"
    path: "data/raw/geospatial/grid.shp"
  - name: "parks"
    path: "data/raw/geospatial/parks.shp"
  - name: "quartiers"
    path: "data/raw/geospatial/quartiers.shp"

