data_dir: "data"
raw_dir: "data/raw"
interim_dir : "data/interim"
processed_dir: "data/processed"
db_dir: "data/db"
scripts_dir: "../scripts" # Adjusted path to scripts directory

raw_shp_path : "data/raw/geospatial"
int_shp_path: "data/interim/geospatial"

raw_gbif_path: "data/raw/gbif" 
int_gbif_path: "data/interim/gbif" 


limit: None
target_crs: 4326

duckdb_file: "data/db/mtlBio.duckdb"

grid_size: 250

taxa_filter : ['phylum', 'Tracheophyta']

gbif_columns: "gbifID,
                occurrenceID,
                kingdom,
                phylum,
                class,
                order,
                family,
                genus,
                species,
                taxonRank,
                scientificName,
                eventDate,
                day,
                month,
                year,
                taxonKey,
                basisOfRecord,
                license,
                recordedBy,
                issue,
                publishingOrgKey,
                coordinateUncertaintyInMeters,
                geom
                "
               